version: '3.8'

services:
  database:
    build: ./database
    container_name: saas-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-strongpassword123}
      POSTGRES_DB: ${POSTGRES_DB:-saasdb}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-saasdb}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: saas-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-strongpassword123}@database:5432/${POSTGRES_DB:-saasdb}?schema=public}
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: saas-frontend
    ports:
      - "3001:3000"  # Next.js por defecto en 3000, mapeado a 3001
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://backend:3000}
    depends_on:
      - backend

volumes:
  db-data: