version: '3.8'

services:
  database:
    build: ./database
    container_name: saas-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: saasdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d saasdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: saas-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user:password@database:5432/saasdb?schema=public"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: saas-frontend
    ports:
      - "3001:3000"  # Next.js por defecto en 3000, mapeado a 3001 para evitar conflicto
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:3000"
    depends_on:
      - backend

volumes:
  db-data: